
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kagan
 */

    




public class MusteriEkrani extends javax.swing.JFrame {
static DefaultListModel<String> model3 =new DefaultListModel<String>();
 public static String kalkis="Kocaeli";
 public static String varis="Konya";
 int j=0;
 Vehicle seciliVehicle=new Vehicle() {
    @Override
    double calculateFuelCost() {
        return 0;
    }
 };
  int secilisefer=-1;
  int koltuksayisi=-1;
  Transport transport=new Transport();
  ArrayList<Vehicle> yenilenenlist=new ArrayList<>();

    public ArrayList<Vehicle> getYenilenenlist() {
        return yenilenenlist;
    }

    public void setYenilenenlist(ArrayList<Vehicle> yenilenenlist) {
        this.yenilenenlist = yenilenenlist;
    }
  

 
    /**
     * Creates new form MusteriEkrani
     */
    public MusteriEkrani() {
        initComponents();
        koltukrb1.setVisible(false);
        koltukrb2.setVisible(false);
        koltukrb3.setVisible(false);
        koltukrb4.setVisible(false);
        koltukrb5.setVisible(false);
        koltukrb6.setVisible(false);
        koltukrb7.setVisible(false);
        koltukrb8.setVisible(false);
        koltukrb9.setVisible(false);
        koltukrb10.setVisible(false);
        koltukrb11.setVisible(false);
        koltukrb12.setVisible(false);
        koltukrb13.setVisible(false);
        koltukrb14.setVisible(false);
        koltukrb15.setVisible(false);
        koltukrb16.setVisible(false);
        koltukrb17.setVisible(false);
        koltukrb18.setVisible(false);
        koltukrb19.setVisible(false);
        koltukrb20.setVisible(false);
        koltukrb21.setVisible(false);
        koltukrb22.setVisible(false);
        koltukrb23.setVisible(false);
        koltukrb24.setVisible(false);
        koltukrb25.setVisible(false);
        koltukrb26.setVisible(false);
        koltukrb27.setVisible(false);
        koltukrb28.setVisible(false);
        koltukrb29.setVisible(false);
        koltukrb30.setVisible(false);
        koltuksecbutonu.setVisible(false);
        odemeyapbutonu.setVisible(false);
        sefersecbutonu.setVisible(false);
        RezervasyonSeferSecmeList.setModel(model3);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tarihcb = new javax.swing.JComboBox<>();
        kalkisnoktasicb = new javax.swing.JComboBox<>();
        varisnoktasicb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        seferbulbutonu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RezervasyonSeferSecmeList = new javax.swing.JList<>();
        sefersecbutonu = new javax.swing.JButton();
        koltukrb1 = new javax.swing.JRadioButton();
        koltukrb2 = new javax.swing.JRadioButton();
        koltukrb24 = new javax.swing.JRadioButton();
        koltukrb3 = new javax.swing.JRadioButton();
        koltukrb4 = new javax.swing.JRadioButton();
        koltukrb5 = new javax.swing.JRadioButton();
        koltukrb6 = new javax.swing.JRadioButton();
        koltukrb16 = new javax.swing.JRadioButton();
        koltukrb7 = new javax.swing.JRadioButton();
        koltukrb8 = new javax.swing.JRadioButton();
        koltukrb9 = new javax.swing.JRadioButton();
        koltukrb10 = new javax.swing.JRadioButton();
        koltukrb11 = new javax.swing.JRadioButton();
        koltukrb15 = new javax.swing.JRadioButton();
        koltukrb12 = new javax.swing.JRadioButton();
        koltukrb13 = new javax.swing.JRadioButton();
        koltukrb14 = new javax.swing.JRadioButton();
        koltukrb28 = new javax.swing.JRadioButton();
        koltukrb19 = new javax.swing.JRadioButton();
        koltukrb20 = new javax.swing.JRadioButton();
        koltukrb17 = new javax.swing.JRadioButton();
        koltukrb21 = new javax.swing.JRadioButton();
        koltukrb18 = new javax.swing.JRadioButton();
        koltukrb22 = new javax.swing.JRadioButton();
        koltukrb23 = new javax.swing.JRadioButton();
        koltukrb27 = new javax.swing.JRadioButton();
        koltukrb29 = new javax.swing.JRadioButton();
        koltukrb25 = new javax.swing.JRadioButton();
        koltukrb26 = new javax.swing.JRadioButton();
        koltukrb30 = new javax.swing.JRadioButton();
        koltuksecbutonu = new javax.swing.JButton();
        odemeyapbutonu = new javax.swing.JButton();
        geributon4 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rezervia");
        setLocation(new java.awt.Point(200, 80));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N

        tarihcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 Aralık", "5 Aralık", "6 Aralık", "7 Aralık", "8 Aralık", "9 Aralık", "10 Aralık" }));

        kalkisnoktasicb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul", "Bilecik", "Kocaeli", "Ankara", "Eskisehir", "Konya" }));

        varisnoktasicb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul", "Bilecik", "Kocaeli", "Ankara", "Eskisehir", "Konya" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Rezervasyon Yap");

        seferbulbutonu.setText("Sefer Bul");
        seferbulbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seferbulbutonuActionPerformed(evt);
            }
        });

        RezervasyonSeferSecmeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(RezervasyonSeferSecmeList);

        sefersecbutonu.setText("Sefer Seç");
        sefersecbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sefersecbutonuActionPerformed(evt);
            }
        });

        buttonGroup1.add(koltukrb1);
        koltukrb1.setText("1.Koltuk");

        buttonGroup1.add(koltukrb2);
        koltukrb2.setText("2.Koltuk");

        buttonGroup1.add(koltukrb24);
        koltukrb24.setText("24.Koltuk");

        buttonGroup1.add(koltukrb3);
        koltukrb3.setText("3.Koltuk");

        buttonGroup1.add(koltukrb4);
        koltukrb4.setText("4.Koltuk");

        buttonGroup1.add(koltukrb5);
        koltukrb5.setText("5.Koltuk");

        buttonGroup1.add(koltukrb6);
        koltukrb6.setText("6.Koltuk");

        buttonGroup1.add(koltukrb16);
        koltukrb16.setText("16.Koltuk");

        buttonGroup1.add(koltukrb7);
        koltukrb7.setText("7.Koltuk");

        buttonGroup1.add(koltukrb8);
        koltukrb8.setText("8.Koltuk");

        buttonGroup1.add(koltukrb9);
        koltukrb9.setText("9.Koltuk");

        buttonGroup1.add(koltukrb10);
        koltukrb10.setText("10.Koltuk");

        buttonGroup1.add(koltukrb11);
        koltukrb11.setText("11.Koltuk");

        buttonGroup1.add(koltukrb15);
        koltukrb15.setText("15.Koltuk");

        buttonGroup1.add(koltukrb12);
        koltukrb12.setText("12.Koltuk");

        buttonGroup1.add(koltukrb13);
        koltukrb13.setText("13.Koltuk");

        buttonGroup1.add(koltukrb14);
        koltukrb14.setText("14.Koltuk");

        buttonGroup1.add(koltukrb28);
        koltukrb28.setText("28.Koltuk");

        buttonGroup1.add(koltukrb19);
        koltukrb19.setText("19.Koltuk");

        buttonGroup1.add(koltukrb20);
        koltukrb20.setText("20.Koltuk");

        buttonGroup1.add(koltukrb17);
        koltukrb17.setText("17.Koltuk");

        buttonGroup1.add(koltukrb21);
        koltukrb21.setText("21.Koltuk");

        buttonGroup1.add(koltukrb18);
        koltukrb18.setText("18.Koltuk");

        buttonGroup1.add(koltukrb22);
        koltukrb22.setText("22.Koltuk");

        buttonGroup1.add(koltukrb23);
        koltukrb23.setText("23.Koltuk");

        buttonGroup1.add(koltukrb27);
        koltukrb27.setText("27.Koltuk");

        buttonGroup1.add(koltukrb29);
        koltukrb29.setText("29.Koltuk");

        buttonGroup1.add(koltukrb25);
        koltukrb25.setText("25.Koltuk");

        buttonGroup1.add(koltukrb26);
        koltukrb26.setText("26.Koltuk");

        buttonGroup1.add(koltukrb30);
        koltukrb30.setText("30.Koltuk");

        koltuksecbutonu.setText("Koltuk Seç");
        koltuksecbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koltuksecbutonuActionPerformed(evt);
            }
        });

        odemeyapbutonu.setText("Ödeme Yap");
        odemeyapbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemeyapbutonuActionPerformed(evt);
            }
        });

        geributon4.setText("Geri Git");
        geributon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geributon4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(sefersecbutonu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tarihcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kalkisnoktasicb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varisnoktasicb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(seferbulbutonu))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(odemeyapbutonu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(koltukrb19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(koltukrb25, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb29, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb21, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(koltukrb30, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb26, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb22, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(koltukrb2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(koltuksecbutonu))
                                        .addGap(256, 256, 256)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(koltukrb24, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb20, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb28, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(koltukrb4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geributon4)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(geributon4))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarihcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kalkisnoktasicb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varisnoktasicb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sefersecbutonu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(seferbulbutonu)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb17)
                            .addComponent(koltukrb18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koltukrb30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(koltukrb29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(koltuksecbutonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(odemeyapbutonu)
                        .addGap(154, 154, 154)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void sefersecbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sefersecbutonuActionPerformed
    sefersecbutonu.setVisible(false);
    
    Transport transport=new Transport();
    ArrayList<Vehicle> kullanilacakaraclist=new ArrayList<>();
    kullanilacakaraclist=getYenilenenlist();
    
   secilisefer=RezervasyonSeferSecmeList.getSelectedIndex();
   koltuksayisi=kullanilacakaraclist.get(secilisefer).seatCapacity;
   Reservation.setSeferno(kullanilacakaraclist.get(secilisefer).chosenTrip.tripName);

   
    
   
    
   
    if(koltuksayisi==15){
        koltukrb1.setVisible(true);
        koltukrb2.setVisible(true);
        koltukrb3.setVisible(true);
        koltukrb4.setVisible(true);
        koltukrb5.setVisible(true);
        koltukrb6.setVisible(true);
        koltukrb7.setVisible(true);
        koltukrb8.setVisible(true);
        koltukrb9.setVisible(true);
        koltukrb10.setVisible(true);
        koltukrb11.setVisible(true);
        koltukrb12.setVisible(true);
        koltukrb13.setVisible(true);
        koltukrb14.setVisible(true);
        koltukrb15.setVisible(true);
         koltukrb16.setVisible(false);
        koltukrb17.setVisible(false);
        koltukrb18.setVisible(false);
        koltukrb19.setVisible(false);
        koltukrb20.setVisible(false);
        koltukrb21.setVisible(false);
        koltukrb22.setVisible(false);
        koltukrb23.setVisible(false);
        koltukrb24.setVisible(false);
        koltukrb25.setVisible(false);
         koltukrb26.setVisible(false);
        koltukrb27.setVisible(false);
        koltukrb28.setVisible(false);
        koltukrb29.setVisible(false);
        koltukrb30.setVisible(false);
    
        
        
        
        
        koltuksecbutonu.setVisible(true);
     
      if(kullanilacakaraclist.get(secilisefer).seats[0]==1){
    koltukrb1.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[1]==1){
    koltukrb2.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[2]==1){
    koltukrb3.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[3]==1){
    koltukrb4.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[4]==1){
    koltukrb5.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[5]==1){
    koltukrb6.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[6]==1){
    koltukrb7.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[7]==1){
    koltukrb8.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[8]==1){
    koltukrb9.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[9]==1){
    koltukrb10.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[10]==1){
    koltukrb11.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[11]==1){
    koltukrb12.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[12]==1){
    koltukrb13.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[13]==1){
    koltukrb14.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[14]==1){
    koltukrb15.setEnabled(false);
    } 
        
     
     
     
     
     
     
    }else if(koltuksayisi==20){
        koltukrb1.setVisible(true);
        koltukrb2.setVisible(true);
        koltukrb3.setVisible(true);
        koltukrb4.setVisible(true);
        koltukrb5.setVisible(true);
        koltukrb6.setVisible(true);
        koltukrb7.setVisible(true);
        koltukrb8.setVisible(true);
        koltukrb9.setVisible(true);
        koltukrb10.setVisible(true);
        koltukrb11.setVisible(true);
        koltukrb12.setVisible(true);
        koltukrb13.setVisible(true);
        koltukrb14.setVisible(true);
        koltukrb15.setVisible(true);
        koltukrb16.setVisible(true);
        koltukrb17.setVisible(true);
        koltukrb18.setVisible(true);
        koltukrb19.setVisible(true);
        koltukrb20.setVisible(true);
        koltukrb21.setVisible(false);
        koltukrb22.setVisible(false);
        koltukrb23.setVisible(false);
        koltukrb24.setVisible(false);
        koltukrb25.setVisible(false);
         koltukrb26.setVisible(false);
        koltukrb27.setVisible(false);
        koltukrb28.setVisible(false);
        koltukrb29.setVisible(false);
        koltukrb30.setVisible(false);
        
      if(kullanilacakaraclist.get(secilisefer).seats[0]==1){
    koltukrb1.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[1]==1){
    koltukrb2.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[2]==1){
    koltukrb3.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[3]==1){
    koltukrb4.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[4]==1){
    koltukrb5.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[5]==1){
    koltukrb6.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[6]==1){
    koltukrb7.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[7]==1){
    koltukrb8.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[8]==1){
    koltukrb9.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[9]==1){
    koltukrb10.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[10]==1){
    koltukrb11.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[11]==1){
    koltukrb12.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[12]==1){
    koltukrb13.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[13]==1){
    koltukrb14.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[14]==1){
    koltukrb15.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[15]==1){
    koltukrb16.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[16]==1){
    koltukrb17.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[17]==1){
    koltukrb18.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[18]==1){
    koltukrb19.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[19]==1){
    koltukrb20.setEnabled(false);
    }
        
        
 
     koltuksecbutonu.setVisible(true);
    }else if(koltuksayisi==25){
         koltukrb1.setVisible(true);
        koltukrb2.setVisible(true);
        koltukrb3.setVisible(true);
        koltukrb4.setVisible(true);
        koltukrb5.setVisible(true);
        koltukrb6.setVisible(true);
        koltukrb7.setVisible(true);
        koltukrb8.setVisible(true);
        koltukrb9.setVisible(true);
        koltukrb10.setVisible(true);
        koltukrb11.setVisible(true);
        koltukrb12.setVisible(true);
        koltukrb13.setVisible(true);
        koltukrb14.setVisible(true);
        koltukrb15.setVisible(true);
        koltukrb16.setVisible(true);
        koltukrb17.setVisible(true);
        koltukrb18.setVisible(true);
        koltukrb19.setVisible(true);
        koltukrb20.setVisible(true);
        koltukrb21.setVisible(true);
        koltukrb22.setVisible(true);
        koltukrb23.setVisible(true);
        koltukrb24.setVisible(true);
        koltukrb25.setVisible(true);
          koltukrb26.setVisible(false);
        koltukrb27.setVisible(false);
        koltukrb28.setVisible(false);
        koltukrb29.setVisible(false);
        koltukrb30.setVisible(false);
        
      if(kullanilacakaraclist.get(secilisefer).seats[0]==1){
    koltukrb1.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[1]==1){
    koltukrb2.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[2]==1){
    koltukrb3.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[3]==1){
    koltukrb4.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[4]==1){
    koltukrb5.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[5]==1){
    koltukrb6.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[6]==1){
    koltukrb7.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[7]==1){
    koltukrb8.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[8]==1){
    koltukrb9.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[9]==1){
    koltukrb10.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[10]==1){
    koltukrb11.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[11]==1){
    koltukrb12.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[12]==1){
    koltukrb13.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[13]==1){
    koltukrb14.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[14]==1){
    koltukrb15.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[15]==1){
    koltukrb16.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[16]==1){
    koltukrb17.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[17]==1){
    koltukrb18.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[18]==1){
    koltukrb19.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[19]==1){
    koltukrb20.setEnabled(false);
    }  if(kullanilacakaraclist.get(secilisefer).seats[20]==1){
    koltukrb21.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[21]==1){
    koltukrb22.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[22]==1){
    koltukrb23.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[23]==1){
    koltukrb24.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[24]==1){
    koltukrb25.setEnabled(false);
    }
        
        
     koltuksecbutonu.setVisible(true);
    }else if(koltuksayisi==30){
         koltukrb1.setVisible(true);
        koltukrb2.setVisible(true);
        koltukrb3.setVisible(true);
        koltukrb4.setVisible(true);
        koltukrb5.setVisible(true);
        koltukrb6.setVisible(true);
        koltukrb7.setVisible(true);
        koltukrb8.setVisible(true);
        koltukrb9.setVisible(true);
        koltukrb10.setVisible(true);
        koltukrb11.setVisible(true);
        koltukrb12.setVisible(true);
        koltukrb13.setVisible(true);
        koltukrb14.setVisible(true);
        koltukrb15.setVisible(true);
        koltukrb16.setVisible(true);
        koltukrb17.setVisible(true);
        koltukrb18.setVisible(true);
        koltukrb19.setVisible(true);
        koltukrb20.setVisible(true);
        koltukrb21.setVisible(true);
        koltukrb22.setVisible(true);
        koltukrb23.setVisible(true);
        koltukrb24.setVisible(true);
        koltukrb25.setVisible(true);
        koltukrb26.setVisible(true);
        koltukrb27.setVisible(true);
        koltukrb28.setVisible(true);
        koltukrb29.setVisible(true);
        koltukrb30.setVisible(true);
        
        
      if(kullanilacakaraclist.get(secilisefer).seats[0]==1){
    koltukrb1.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[1]==1){
    koltukrb2.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[2]==1){
    koltukrb3.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[3]==1){
    koltukrb4.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[4]==1){
    koltukrb5.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[5]==1){
    koltukrb6.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[6]==1){
    koltukrb7.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[7]==1){
    koltukrb8.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[8]==1){
    koltukrb9.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[9]==1){
    koltukrb10.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[10]==1){
    koltukrb11.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[11]==1){
    koltukrb12.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[12]==1){
    koltukrb13.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[13]==1){
    koltukrb14.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[14]==1){
    koltukrb15.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[15]==1){
    koltukrb16.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[16]==1){
    koltukrb17.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[17]==1){
    koltukrb18.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[18]==1){
    koltukrb19.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[19]==1){
    koltukrb20.setEnabled(false);
    }  if(kullanilacakaraclist.get(secilisefer).seats[20]==1){
    koltukrb21.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[21]==1){
    koltukrb22.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[22]==1){
    koltukrb23.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[23]==1){
    koltukrb24.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[24]==1){
    koltukrb25.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[25]==1){
    koltukrb26.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[26]==1){
    koltukrb27.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[27]==1){
    koltukrb28.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[28]==1){
    koltukrb29.setEnabled(false);
    } if(kullanilacakaraclist.get(secilisefer).seats[29]==1){
    koltukrb30.setEnabled(false);
    }   
        
        
     koltuksecbutonu.setVisible(true);
     
     
    }

    
    
        

        
    }//GEN-LAST:event_sefersecbutonuActionPerformed

    private void koltuksecbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koltuksecbutonuActionPerformed
 
      String kisiler="1";
      int kisis=Integer.parseInt(kisiler);
      Reservation reservation =new Reservation();
    
    int index=RezervasyonSeferSecmeList.getSelectedIndex();
    Transport transport=new Transport();
    ArrayList<Vehicle> kullanilacakaraclist=new ArrayList<>();
    kullanilacakaraclist=getYenilenenlist();
      
          
      String adsoyad= JOptionPane.showInputDialog(this, "Adınızı ve Soyadınızı Girin");
      String tcno= JOptionPane.showInputDialog(this, "TC. Kimlik Numaranızı Girin");
      String dogumtarihi= JOptionPane.showInputDialog(this, "Doğum Tarihinizi Girin");
      Passenger yolcu1=new Passenger(adsoyad,"", tcno, dogumtarihi);
      buttonGroup1.getSelection().setEnabled(false);
      
      if(koltukrb1.isSelected()){     
           reservation.setSeatNumber("1");
           kullanilacakaraclist.get(index).seats[0]=1;
      }else if(koltukrb2.isSelected()){
           reservation.setSeatNumber("2");
           kullanilacakaraclist.get(index).seats[1]=1;
      }else if(koltukrb3.isSelected()){
           reservation.setSeatNumber("3");
           kullanilacakaraclist.get(index).seats[2]=1;
      }else if(koltukrb4.isSelected()){
           reservation.setSeatNumber("4");
           kullanilacakaraclist.get(index).seats[3]=1;
      }else if(koltukrb5.isSelected()){
           reservation.setSeatNumber("5");
           kullanilacakaraclist.get(index).seats[4]=1;
      }else if(koltukrb6.isSelected()){
           reservation.setSeatNumber("6");
           kullanilacakaraclist.get(index).seats[5]=1;
      }else if(koltukrb7.isSelected()){
           reservation.setSeatNumber("7");
           kullanilacakaraclist.get(index).seats[6]=1;
      }else if(koltukrb8.isSelected()){
           reservation.setSeatNumber("8");
           kullanilacakaraclist.get(index).seats[7]=1;
           
      }else if(koltukrb9.isSelected()){
           reservation.setSeatNumber("9");
           kullanilacakaraclist.get(index).seats[8]=1;
      }else if(koltukrb10.isSelected()){
           reservation.setSeatNumber("10");
           kullanilacakaraclist.get(index).seats[9]=1;
      }else if(koltukrb11.isSelected()){
           reservation.setSeatNumber("11");
           kullanilacakaraclist.get(index).seats[10]=1;
      }else if(koltukrb12.isSelected()){
           reservation.setSeatNumber("12");
           kullanilacakaraclist.get(index).seats[11]=1;
      }else if(koltukrb13.isSelected()){
           reservation.setSeatNumber("13");
           kullanilacakaraclist.get(index).seats[12]=1;
      }else if(koltukrb14.isSelected()){
           reservation.setSeatNumber("14");
           kullanilacakaraclist.get(index).seats[13]=1;
      }else if(koltukrb15.isSelected()){
           reservation.setSeatNumber("15");
           kullanilacakaraclist.get(index).seats[14]=1;
      }else if(koltukrb16.isSelected()){
           reservation.setSeatNumber("16");
           kullanilacakaraclist.get(index).seats[15]=1;
      }else if(koltukrb17.isSelected()){
           reservation.setSeatNumber("17");
           kullanilacakaraclist.get(index).seats[16]=1;
      }else if(koltukrb18.isSelected()){
           reservation.setSeatNumber("18");
           kullanilacakaraclist.get(index).seats[17]=1;
      }else if(koltukrb19.isSelected()){
           reservation.setSeatNumber("19");
           kullanilacakaraclist.get(index).seats[18]=1;
      }else if(koltukrb20.isSelected()){
           reservation.setSeatNumber("20");
           kullanilacakaraclist.get(index).seats[19]=1;
      }else if(koltukrb21.isSelected()){
           reservation.setSeatNumber("21");
           kullanilacakaraclist.get(index).seats[20]=1;
      }else if(koltukrb22.isSelected()){
           reservation.setSeatNumber("22");
           kullanilacakaraclist.get(index).seats[21]=1;
      }else if(koltukrb23.isSelected()){
           reservation.setSeatNumber("23");
           kullanilacakaraclist.get(index).seats[22]=1;
      }else if(koltukrb24.isSelected()){
           reservation.setSeatNumber("24");
           kullanilacakaraclist.get(index).seats[23]=1;
      }else if(koltukrb25.isSelected()){
           reservation.setSeatNumber("25");
           kullanilacakaraclist.get(index).seats[24]=1;
      }else if(koltukrb26.isSelected()){
           reservation.setSeatNumber("26");
           kullanilacakaraclist.get(index).seats[25]=1;
      }else if(koltukrb27.isSelected()){
           reservation.setSeatNumber("27");
           kullanilacakaraclist.get(index).seats[26]=1;
      }else if(koltukrb28.isSelected()){
           reservation.setSeatNumber("28");
           kullanilacakaraclist.get(index).seats[27]=1;
      }else if(koltukrb29.isSelected()){
           reservation.setSeatNumber("29");
           kullanilacakaraclist.get(index).seats[28]=1;
      }else if(koltukrb30.isSelected()){
          
           reservation.setSeatNumber("30");
           kullanilacakaraclist.get(index).seats[29]=1;
      }else{
      JOptionPane.showMessageDialog(this, "Koltuk seçmediniz");
      }
        if(j==0){
            Transport.setPassenger(yolcu1);
            if(kisis==1){
            koltuksecbutonu.setVisible(false);
            odemeyapbutonu.setVisible(true);
            }
        }else if(j==1){
            Transport.setPassenger1(yolcu1);
            koltuksecbutonu.setVisible(false);
            odemeyapbutonu.setVisible(true);
        }
       j++;
      Reservation.setPassenger(yolcu1);
      Reservation.setUcret(kullanilacakaraclist.get(secilisefer).customerPay);
      
      int i=0;
      for(Vehicle arac:kullanilacakaraclist){
      
      if(kullanilacakaraclist.get(secilisefer).namecompany.equals(Company.GlobalArrayList.getGlobalList().get(i).companyname)){
      Company.GlobalArrayList.getGlobalList().get(i).profit+=Reservation.getUcret();
      }
      
      }
      
              {
              }       
     
      
      
    }//GEN-LAST:event_koltuksecbutonuActionPerformed

    
    
    
   
    private void odemeyapbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeyapbutonuActionPerformed
        
        
        BiletBilgisiPaneli biletBilgisiPaneli=new BiletBilgisiPaneli();
        setVisible(true);
        biletBilgisiPaneli.setVisible(true);
        
    }//GEN-LAST:event_odemeyapbutonuActionPerformed

    private void seferbulbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seferbulbutonuActionPerformed
         model3.clear();
         //seferbulbutonu.setVisible(false);
         sefersecbutonu.setVisible(true);
         kalkis=(String)kalkisnoktasicb.getSelectedItem();
         varis=(String)varisnoktasicb.getSelectedItem();
         String tarih=(String)tarihcb.getSelectedItem();
         String kisisayisi="1";
         Reservation.yolcusayisi=kisisayisi;
         Reservation.kalkis=kalkis;
         Reservation.varis=varis;
         Reservation.tarih=tarih;
  Transport transport=new Transport(); 
  ArrayList<Vehicle> araclist=new ArrayList<>();
  ArrayList<Vehicle> gonderilecekaraclist=new ArrayList<>();
        
         araclist=transport.getVehicleList();
         gonderilecekaraclist.clear();
        for(Vehicle arac :araclist ){
            if(findVehicle(arac)==2){
            model3.addElement(arac.namecompany+" Firmasi "+arac.vehicleName+" "+arac.seatCapacity+" kisilik");
            gonderilecekaraclist.add(arac);
            }  
        }
        setYenilenenlist(gonderilecekaraclist);
        for(Vehicle arac :araclist ){
            if(arac.vehicleName.contains("Otobus")){
            arac.chosenRoute.startPoint = kalkis;
            arac.chosenRoute.endPoint = varis;
            arac.chosenRoute.result= arac.chosenRoute.customerPayHighway(kalkis, varis);
            for (int value : arac.chosenRoute.result) {
           
        }
            arac.customerPay =arac.chosenRoute.result[0];
            arac.distance = arac.chosenRoute.result[1];
            //System.out.println("gidilecek mesafe"+arac.distance);
            arac.totalfuelCost = arac.calculateFuelCost();
           // System.out.println("fuel cost"+arac.fuelCost);
          }
            else if(arac.vehicleName.contains("Ucak")){
            arac.chosenRoute.startPoint = kalkis;
            arac.chosenRoute.endPoint = varis;
            arac.chosenRoute.result= arac.chosenRoute.customerPayAirway(kalkis, varis);
            for (int value : arac.chosenRoute.result) {
            
        }
            arac.customerPay =arac.chosenRoute.result[0];
            arac.distance = arac.chosenRoute.result[1];
            //System.out.println("gidilecek mesafe"+arac.distance);
            arac.totalfuelCost = arac.calculateFuelCost();
           // System.out.println("fuel cost"+arac.fuelCost);
          }
            else if(arac.vehicleName.contains("Tren")){
            arac.chosenRoute.startPoint = kalkis;
            arac.chosenRoute.endPoint = varis;
            arac.chosenRoute.result= arac.chosenRoute.customerPayRailway(kalkis, varis);
            for (int value : arac.chosenRoute.result) {
          
        }
            arac.customerPay =arac.chosenRoute.result[0];
            arac.distance = arac.chosenRoute.result[1];
            //System.out.println("gidilecek mesafe"+arac.distance);
            arac.totalfuelCost = arac.calculateFuelCost();
           // System.out.println("fuel cost"+arac.fuelCost);
          }
        }
        
koltukrb1.setEnabled(true);
koltukrb2.setEnabled(true);
koltukrb3.setEnabled(true);
koltukrb4.setEnabled(true);
koltukrb5.setEnabled(true);
koltukrb6.setEnabled(true);
koltukrb7.setEnabled(true);
koltukrb8.setEnabled(true);
koltukrb9.setEnabled(true);
koltukrb10.setEnabled(true);
koltukrb11.setEnabled(true);
koltukrb12.setEnabled(true);
koltukrb13.setEnabled(true);
koltukrb14.setEnabled(true);
koltukrb15.setEnabled(true);
koltukrb16.setEnabled(true);
koltukrb17.setEnabled(true);
koltukrb18.setEnabled(true);
koltukrb19.setEnabled(true);
koltukrb20.setEnabled(true);
koltukrb21.setEnabled(true);
koltukrb22.setEnabled(true);
koltukrb23.setEnabled(true);
koltukrb24.setEnabled(true);
koltukrb25.setEnabled(true);
koltukrb26.setEnabled(true);
koltukrb27.setEnabled(true);
koltukrb28.setEnabled(true);
koltukrb29.setEnabled(true);
koltukrb30.setEnabled(true);


         
    }//GEN-LAST:event_seferbulbutonuActionPerformed

    private void geributon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geributon4ActionPerformed
        setVisible(false);
        AnaEkran anaEkran=new AnaEkran();
        anaEkran.setVisible(true);
    }//GEN-LAST:event_geributon4ActionPerformed

    public static int findVehicle(Vehicle vehicle){
     
    String aranan = vehicle.chosenTrip.city;
    
    if (aranan.contains(kalkis) && aranan.contains(varis)){
        return 2;
    }
    return -1;
  }



    /**
     * @param args the command line arguments
     */




    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 

    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriEkrani().setVisible(true);
          
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> RezervasyonSeferSecmeList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton geributon4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> kalkisnoktasicb;
    private javax.swing.JRadioButton koltukrb1;
    private javax.swing.JRadioButton koltukrb10;
    private javax.swing.JRadioButton koltukrb11;
    private javax.swing.JRadioButton koltukrb12;
    private javax.swing.JRadioButton koltukrb13;
    private javax.swing.JRadioButton koltukrb14;
    private javax.swing.JRadioButton koltukrb15;
    private javax.swing.JRadioButton koltukrb16;
    private javax.swing.JRadioButton koltukrb17;
    private javax.swing.JRadioButton koltukrb18;
    private javax.swing.JRadioButton koltukrb19;
    private javax.swing.JRadioButton koltukrb2;
    private javax.swing.JRadioButton koltukrb20;
    private javax.swing.JRadioButton koltukrb21;
    private javax.swing.JRadioButton koltukrb22;
    private javax.swing.JRadioButton koltukrb23;
    private javax.swing.JRadioButton koltukrb24;
    private javax.swing.JRadioButton koltukrb25;
    private javax.swing.JRadioButton koltukrb26;
    private javax.swing.JRadioButton koltukrb27;
    private javax.swing.JRadioButton koltukrb28;
    private javax.swing.JRadioButton koltukrb29;
    private javax.swing.JRadioButton koltukrb3;
    private javax.swing.JRadioButton koltukrb30;
    private javax.swing.JRadioButton koltukrb4;
    private javax.swing.JRadioButton koltukrb5;
    private javax.swing.JRadioButton koltukrb6;
    private javax.swing.JRadioButton koltukrb7;
    private javax.swing.JRadioButton koltukrb8;
    private javax.swing.JRadioButton koltukrb9;
    private javax.swing.JButton koltuksecbutonu;
    private javax.swing.JButton odemeyapbutonu;
    private javax.swing.JButton seferbulbutonu;
    private javax.swing.JButton sefersecbutonu;
    private javax.swing.JComboBox<String> tarihcb;
    private javax.swing.JComboBox<String> varisnoktasicb;
    // End of variables declaration//GEN-END:variables
}
